### ISSUE TITLE
session을  정지할수있는 방법이 궁금합니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#10]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
![image](https://user-images.githubusercontent.com/46337218/87399626-99b8bd00-c5f2-11ea-8ccb-cee5ee27ec96.png)

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182
**Question**
![image](https://user-images.githubusercontent.com/46337218/87398867-7c372380-c5f1-11ea-8b1b-f3012698e341.png)

submit이 이상하게 된거 같아서 종료를 시키려고 하는데 위와 같이 뜨면서 웹상에서 정지가 되지않습니다.
방법을 알려주시면 감사하겠습니다.

**Comment by bluebrush** [comment]
@hjlee9182 님, submit으로 제출된 이후에는 멈출수가 없습니다. 
submit 과정의 문제를 사전에 알아보기 위해서, test-submit이 있으니 활용하시면 좋을 듯 합니다. 
submit 세션은 최대 1시간이 이후 자동 종료 되며, submit 제출 시간 간격도 1시간이니 이부분도 참고바랍니다.

**Comment by hjlee9182** [comment]
@bluebrush 
현재 아까 submit 한 세션들이 3시간이 지나도 살아있는데 혹시 한번 확인해주실수 있으신가요??..

**Comment by bluebrush** [comment]
@hjlee9182 님, 
nsml rm -f [sessionID] 로 강제삭제하였습니다. 
혹시, 동일 이슈 있으시면 nsml rm -f  시도 부탁드립니다.

**Comment by hjlee9182** [comment]
@bluebrush  감사합니다.
