### ISSUE TITLE
submit 시 shm-size 설정

### ISSUE THREAD

**Issue by jzi040941** [AI-RUSH-Operation/NAVER-AI-RUSH#100]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Ubuntu
- **client version(please show nsml --version)**: 
Built: 2020-07-16T14:06:32+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: linux
Revision: abae53dd3589a47d7f89a40128cb86176123f7ec (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**: 
- **URL**:

**What is your login ID?** jzi040941

**Question**
submit 시 shm-size 부족으로 에러가 발생하는데
submit 하는 session의 shm-size 속성을 그대로 받아오는 것인가요?
그게 아니라면 submit 시에 shm-size를 설정하는 방법이 있는지 궁금합니다.

**Comment by nsml-admin** [comment]
안녕하세요.

submit하는 session 의  shm-size속성을 그대로 받아오게 되어있습니다.
