### ISSUE TITLE
할당하지 않은 자원이 할당되었다고 나옵니다.

### ISSUE THREAD

**Issue by Ye-Ji-Kim** [AI-RUSH-Operation/NAVER-AI-RUSH#104]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Ye-Ji-Kim

**Question**
Session을 아무것도 돌리고 있지 않은 상황에서 gpu 1개, cpu 5개, 메모리 50G가 할당되어있다고 나옵니다. 세션을 다 확인해보아도 확인 당시 running 중이거나 allocated 된 세션은 없었습니다. 확인 부탁드립니다.

**Comment by justHungryMan** [comment]
@Ye-Ji-Kim nsml ps 를 하시면 현재 진행중인 세션목록이 나옵니다.
추가로 nsml rm -f {session ID} 를 하시면 세션 종료 됩니다.

**Comment by Ye-Ji-Kim** [comment]
해결했습니다. 감사합니다!!
