### ISSUE TITLE
제출마감시간 관련

### ISSUE THREAD

**Issue by ddamddi** [AI-RUSH-Operation/NAVER-AI-RUSH#105]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**
1라운드가 금일(31일) 오후6시 마감으로 알고있는데, 오후 6시 이전에 submit한 Session까지 인정되는 것인가요? 아니면 Inferred되서 랭킹에 6시이전에 반영이 되야 인정되는 것인가요??

**Comment by bluebrush** [comment]
@ddamddi 님, infer 완료되고, leaderboard에 기록까지 6시에 끝나야합니다.
