### ISSUE TITLE
nsml은 언제까지 활용할 수 있나요?

### ISSUE THREAD

**Issue by jung-hunsoo** [AI-RUSH-Operation/NAVER-AI-RUSH#106]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
> Built: 2020-07-30T13:35:49+09:00

#### WEB
- **Brower (chrome, firfox, etc)**: Chrome
- **URL**:

**What is your login ID?**
> jung-hunsoo

**Question**
 1라운드의 마감과 별개로 돌리는 모델을 좀 더 학습시켜 결과를 보고 싶은데, 세션과 자원 접근은 언제까지 가능한지 문의드립니다.

 And, 만약 가능하다면 주말까지라도 (submit을 제외한) 연습을 더 해보고 싶은데, 접근 권한 연장이 가능한지 궁금합니다. (아마 많은 분들이 같은 마음일 것 같습니다!)

**Comment by bluebrush** [comment]
@jung-hunsoo 님, 아쉽지만, round1은 여기까지 사용하도록 하겠습니다. 내부에서 정리도 하고, round2 준비도 해야해서 system사용은 제한할 예정입니다.

**Comment by jung-hunsoo** [comment]
예 답변 감사합니다~
