### ISSUE TITLE
PyTorch / Docker 사용과 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by wookiekim** [AI-RUSH-Operation/NAVER-AI-RUSH#11]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Ubuntu 18.04.4
- **client version(please show nsml --version)**: 

```
Built: 2020-07-13T19:30:15+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: linux
Revision: dd3f91164a969f04d70f870cd2e42001db47b504 (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001
```

#### WEB
- **Brower (chrome, firfox, etc)**: Chrome
- **URL**:  

**What is your login ID?** : wookiekim

**Question**
Documentation의 [Prepare a session environment](https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/prepare_a_session_environment.html)를 보면, pip/apt-get을 사용하거나, docker를 사용하는 방법이 기재되어있습니다.

QnA세션 도중 PyTorch를 사용해도 괜찮을지에 대한 질문에, Docker를 맞춰서 사용해주면 된다고 답변해주셨는데요. 현재 NSML의 Docker Images에는 아무것도 나와있지 않아서, 현재 baseline 에 주어진 docker image (nsml:registry.navercorp.com/nsml/airush2020:tf2.0) 외에는 어떻게 사용해야 할지 잘 모르겠습니다.

pip으로 PyTorch를 추가로 설치하는 방향으로 진행하면 되는것인지, 아니라면 Docker Image들이 추가 중에 있는 것인지 궁금합니다.

**Comment by bluebrush** [comment]
@wookiekim 님, 
https://airush.nsml.navercorp.com/support 하위 Docker Image에 일부 이미지가 추가되었습니다.

**Comment by wookiekim** [comment]
@bluebrush 감사합니다, 확인했습니다. 다만 Pytorch가 설치되어있는 docker image는 없는 것으로 보이는데, 직접 설치해서 사용하면 되는건가요?

감사합니다.

**Comment by developer0hye** [comment]
@wookiekim 

저같은 경우 토치 설치를 위해 아래와 같이 setup.py 와 requirements.txt 를 수정하였습니다.
이후 세션을 실행시켜보니 별다른 오류는 출력되지 않은 걸로 보아 설치에 성공한 것 같습니다!

setup.py
```
# nsml: registry.navercorp.com/nsml/airush2020:tf2.0
from distutils.core import setup

setup(
    name="Spam classification - AI Rush baseline",
    version="1",
    install_requires=['cachetools==4.1.0',
                      'fire==0.3.1',
                      'h5py==2.7.1',
                      'matplotlib==3.2.2',
                      'scikit-learn==0.23.1',
                      'keras==2.3.1',
                      'keras_applications==1.0.8',
                      'keras_metrics==1.1.0',
                      'torch',
                      'opencv-python',
                      'torchvision',
                      'numpy==1.19.0',
                      'pandas==1.0.5',
                      'pillow==7.1.2',
                      'requests==2.24.0',
                      'tqdm==4.46.1',
                      'wget==3.2',
                      'visdom==0.1.8.9']
)
```

requirements.txt
```
cachetools==4.1.0
fire==0.3.1
h5py==2.7.1
matplotlib==3.2.2
scikit-learn==0.23.1
numpy==1.19.0
pandas==1.0.5
pillow==7.1.2
requests==2.24.0
tqdm==4.46.1
wget==3.2
visdom==0.1.8.9
torch
opencv-python
torchvision
```

**Comment by wookiekim** [comment]
PyTorch 사용건에 대한 issue는 해결된 것 같아 닫겠습니다.
