### ISSUE TITLE
Image Sample.

### ISSUE THREAD

**Issue by justHungryMan** [AI-RUSH-Operation/NAVER-AI-RUSH#12]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
justHungryMan

**Question**

train data 에서 labeled, unlabeled data, test data 에서의 샘플 데이터를 공개해주신다고 하셨는데 어떻게 볼 수 있는지 알고싶습니다.

**Comment by bluebrush** [comment]
@justHungryMan 님, 추가 작업중입니다.

**Comment by bluebrush** [comment]
@justHungryMan 님, readme에 update되었습니다. 
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/tree/master/spam
