### ISSUE TITLE
nsml run 에러가 발생합니다.

### ISSUE THREAD

**Issue by DaeHwanGi** [AI-RUSH-Operation/NAVER-AI-RUSH#14]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: macOS version 10.15.5
- **client version(please show nsml --version)**: 

Built: 2020-07-13T19:30:15+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: darwin
Revision: dd3f91164a969f04d70f870cd2e42001db47b504 (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Daehwangi

**Question**

#7 과 동일하게 로그인 이후 nsml run으로 세션을 생성할 때 오류가 발생합니다.
nsml 재설치 이후에도 증상이 동일합니다.

~~~
.Error: An error occurred while initializing user information. Please contact dev team
FATA[2020/07/14 20:30:26.344] Internal server error
~~~

**Comment by nsml-admin** [comment]
해결되었습니다. 다시 시도해 보시기 바랍니다.
