### ISSUE TITLE
로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by Ye-Ji-Kim** [AI-RUSH-Operation/NAVER-AI-RUSH#15]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Ye-Ji-Kim

**Question**
로그인 시도 시 다음과 같은 메시지가 뜨며 로그인이 되지 않습니다.
You are not a registered user

**Comment by bluebrush** [comment]
@Ye-Ji-Kim 님, 
nsml login 시작부터 전체 오류 메시지 부탁드립니다.

**Comment by Ye-Ji-Kim** [comment]
C:\Users\kyeoj\Desktop\AI RUSH\nsml_client.windows.amd64.hack>nsml login
time="2020/07/14 21:01:33.042" level=info msg="connecting to ai-cli.nsml.navercorp.com:443"
GitHub Username: Ye-Ji-Kim
GitHub Password: **********
time="2020/07/14 21:01:48.197" level=fatal msg="login failed: You are not a registered user"

위와 같습니다!

**Comment by bluebrush** [comment]
@Ye-Ji-Kim 님, 
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/1
참고하시어, CLI 다시 다운로드하시기 바랍니다.

**Comment by doljae** [comment]
@bluebrush 
안녕하세요. 동일한 문제를 겪고 있어서 문의 드립니다. 링크 주신 페이지에서 윈도우용 CLI를 다운받고, 압축을 푼 뒤 nsml.exe가 있는 폴더 경로에서 cmd를 통해 실행 후 로그인을 시도하고 있으나 안 되서 문의 남깁니다.

nsml login -e CP949
이후 현재 github의 닉네임(doljae)와 비밀번호를 입력했으나 로그인이 되지 않습니다.

**Comment by doljae** [comment]
@bluebrush 
해결했습니다.

**Comment by Ye-Ji-Kim** [comment]
해결하였습니다. 감사합니다.
