### ISSUE TITLE
nsml 터미널은 없나요?

### ISSUE THREAD

**Issue by IllgamhoDuck** [AI-RUSH-Operation/NAVER-AI-RUSH#16]
**Question**

코드를 완성한 후 `nsml run`으로 실행하는 방식 말고 한줄한줄 코드를 수정해가면서 실행하고 싶은데 별도로 클라우드로 직접 접속 가능한 터미널은 없나요?

**Comment by bluebrush** [comment]
@IllgamhoDuck 님, notebook 같이 수정하면서 실행하는 환경은 이번 AIRUSH에서 제공되지 않습니다.

**Comment by IllgamhoDuck** [comment]
@bluebrush 감사합니다!
