### ISSUE TITLE
Pytorch Reference  코드

### ISSUE THREAD

**Issue by redleaf-kim** [AI-RUSH-Operation/NAVER-AI-RUSH#17]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?** MaiHon

**Question**
BaseLine으로 공유해주신 코드가  TF2.0을 기반으로 작성된 코드인데, Pytorch로 작성된 BaseLine코드는 없나요?
올려주신 코드를 기반으로 뜯어고쳐 Dataloader.py 부분을 작성해야하나요?

**Comment by justHungryMan** [comment]
이 부분에 대해서 코멘트 해주실 수 있나요? TF2.0 을 공부해야하나 해서 지금 진행을 못하고 있습니다.
@nsml-admin

**Comment by redleaf-kim** [comment]
@justHungryMan 

dataloader 부분을 제가 직접작성하긴 했는데... 대회이다보니 공유는 무리인것 같고
팁을 좀 드리겠습니다.

<img width="442" alt="스크린샷 2020-07-15 오후 4 38 42" src="https://user-images.githubusercontent.com/41847456/87517308-a7854580-c6b9-11ea-9d8c-adf849c6fb83.png">


데이터 구조가 이렇게 생겼고
train_label은 확장자 없는  csv파일 이었습니다.

라벨파일안에는 annotation과 filename 두 column으로 구성되있었고,
annotation에는 0, 1, 2, 3 그리고 -1(Unlabeled) 값이 int64값으로 들어있습니다.
filename자체에 확장자가 붙어서 파일을 바로 읽으면 되었습니다.

**Comment by justHungryMan** [comment]
@MaiHon  감사합니다. 도움 많이 되었습니다.
