### ISSUE TITLE
nsml 로그인 문제

### ISSUE THREAD

**Issue by whgusdn321** [AI-RUSH-Operation/NAVER-AI-RUSH#18]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows10
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**:

**What is your login ID?**
whgusdn321

**Question**
안녕하세요, 다름이 아니라 제 아이디로 터미널 상에 nsml 로그인이 안되서 질문드립니다.  제 깃헙 아이디는 whgusdn321 이구요, 깃헙에 등록되 있는 아이디랑 비번이랑 아무리 해봐도 로그인이 안됩니다..
감사합니다
![image](https://user-images.githubusercontent.com/43023361/87437402-3d24c480-c629-11ea-9ed2-fb877d8c972e.png)

**Comment by thisisiron** [comment]
해당 [링크](https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/1#issue-656318534)에서 NSML 다운받아서 한번해보세요.

**Comment by bluebrush** [comment]
@whgusdn321 님, CLI 다시 #1 이슈에 안내된 CLI download 하시어 접속하시면 동작할 것 같습니다. 문의주신 CLI는 다른 인스턴스에 사용되는 것입니다. 웹 UI 주소도 다르니 참고바랍니다.

**Comment by whgusdn321** [comment]
감사합니다 해결되었습니다!
