### ISSUE TITLE
혐오 댓글 과제는 제출 기한이 늘어나나요?

### ISSUE THREAD

**Issue by dhsimpson** [AI-RUSH-Operation/NAVER-AI-RUSH#19]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**

스팸 이미지 과제가 정시에 시작됐고, 혐오 댓글 과제는 아직 시작할 수가 없으니 혐오 댓글 과제는 지연 된 날짜만큼 제출 기한이 늘어나는 건가요?

**Comment by bluebrush** [comment]
@dhsimpson 님, 제출 마감 시간은 동일하게 유지하려고 합니다. 감사합니다.
