### ISSUE TITLE
NSML login 불가

### ISSUE THREAD

**Issue by cybaj** [AI-RUSH-Operation/NAVER-AI-RUSH#2]
### Any other comments
NSML login 이 안되었습니다.
```
$ nsml login
INFO[2020/07/14 14:05:15.291] connecting to airush-cli.nsml.navercorp.com:10001 
GitHub Username: cybaj
GitHub Password: *********
FATA[2020/07/14 14:05:18.714] login failed: You are not a registered user 
```

### nsml 설치
[flova client repo](https://github.com/n-CLAIR/nsml_client-flova) 에서 linux binary 로 접속하였습니다.

개인정보가 필요한 사항이라면, 말씀 주신대로 이메일로 답변 드릴 수 있습니다.

**Comment by bluebrush** [comment]
@cybaj 님, 다시 시도 해보실수 있을까요?

**Comment by cybaj** [comment]
@bluebrush 감사합니다! 되었습니다.
