### ISSUE TITLE
로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by teang1995** [AI-RUSH-Operation/NAVER-AI-RUSH#20]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:  Window8
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**:

**What is your login ID?**
teang1995

**Question**
documentation에 제시된 방식대로 진행하였는데 로그인이 정상적으로 되지 않습니다. 
qna에 올라온 답변 링크의 NSML 파일을 다운 받아 실행했습니다. 
혹시 제가 잘못한 부분이 있는지 확인해주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/23451721/87459776-cc8ca080-c646-11ea-9a99-eeb33f1a97a9.png)

**Comment by bluebrush** [comment]
@teang1995 님,  아래 단계들에 대한 확인이 필요해 보입니다. (터미널 출력 붙여주시면 확인하겠습니다.)
현재, 방화벽 이슈로 접속이 안되는 것으로 보여집니다. 추가 출력 메시지 부탁드립니다. 
```
ping airush-cli.nsml.navercorp.com
telnet  airush-cli.nsml.navercorp.com 10001
```

**Comment by teang1995** [comment]
![nsml ping](https://user-images.githubusercontent.com/23451721/87497238-282f4c00-c690-11ea-9add-44c83f5264a0.PNG)
![nsml telnet](https://user-images.githubusercontent.com/23451721/87497251-2c5b6980-c690-11ea-8851-aedbe37f5eec.PNG)

telnet은 정확한 확인 방법을 모르겠습니다. ping의 경우 100% 손실됩니다.

**Comment by teang1995** [comment]
![nsml ping](https://user-images.githubusercontent.com/23451721/87497387-66c50680-c690-11ea-93eb-eda25c79d6c5.PNG)
![nsml telnet](https://user-images.githubusercontent.com/23451721/87497391-688eca00-c690-11ea-9948-5e7e93fe066a.PNG)

telnet의 경우 정확한 출력 방식을 모르겠습니다.

**Comment by teang1995** [comment]
방화벽을 제거해도 처음과 같은 출력이 발생하며 로그인이 되지 않습니다.

**Comment by teang1995** [comment]
해결되었습니다. 감사합니다.
