### ISSUE TITLE
로그인 이슈

### ISSUE THREAD

**Issue by doljae** [AI-RUSH-Operation/NAVER-AI-RUSH#21]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**

혹시 동일한 깃허브 계정으로 여러 PC에서 접속하는 것이 가능한가요?
자택 PC에서 어제 로그인이 되는 것을 확인했고, 현재는 다음과 같은 에러가 뜨고 있습니다.
```sh
C:\Users\multicampus>nsml login -e CP949
time="2020/07/15 09:01:39.650" level=info msg="connecting to airush-cli.nsml.navercorp.com:10001"
GitHub Username: doljae
GitHub Password: ************
time="2020/07/15 09:01:59.003" level=fatal msg="could not execute login: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```
```sh
C:\Users\multicampus>nsml login
time="2020/07/15 09:02:28.696" level=info msg="connecting to airush-cli.nsml.navercorp.com:10001"
GitHub Username: doljae
GitHub Password: *************
time="2020/07/15 09:02:46.960" level=fatal msg="could not execute login: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```

**Comment by bluebrush** [comment]
@doljae 님,  아래 단계들에 대한 확인이 필요해 보입니다. (터미널 출력 붙여주시면 확인하겠습니다.)
현재, 방화벽 이슈로 접속이 안되는 것으로 보여집니다. 추가 출력 메시지 부탁드립니다. 
```
ping airush-cli.nsml.navercorp.com
telnet  airush-cli.nsml.navercorp.com 10001
```

**Comment by doljae** [comment]
![캡처](https://user-images.githubusercontent.com/37795866/87498959-0cc64000-c694-11ea-8167-481ed35035d3.PNG)

CMD화면 캡쳐 이미지 입니다.

**Comment by bluebrush** [comment]
@doljae 님, 위 화면은 방화벽 또는 네트웍 접속 문제로 보여집니다. 최근 session run이 확인되는데요, 해결되신 것으로 추정됩니다. 이슈 지속되시면 다시 말씀해주세요.
