### ISSUE TITLE
inspect 명령어에 대한 질문입니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#23]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
![image](https://user-images.githubusercontent.com/46337218/87499166-82321080-c694-11ea-848e-9ce90d82e735.png)

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**

- 다른 분 issue에서 nsml inspect를 사용하신것을 보았는데
![image](https://user-images.githubusercontent.com/46337218/87499316-eead0f80-c694-11ea-8b40-a74a4e7b7241.png)

위와 같이 사용이 되지않습니다.
혹시 해결방법을 알려주시면 감사드리겠습니다.

**Comment by bluebrush** [comment]
@hjlee9182 님, 해당 기능을 사용하실 수 있도록 2:00 ~ 2:30분 사이 CLI 재 배포 예정입니다.

**Comment by hjlee9182** [comment]
감사합니다
