### ISSUE TITLE
--gpu-driver-version flag 관련 질문입니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#24]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**
![image](https://user-images.githubusercontent.com/46337218/87502148-d260a100-c69b-11ea-8971-5f310758661b.png)

새롭게 올려주신 run 명령어를 실행시켰는데 --gpu-driver-version flag때문에 실행이 되지않습니다.
어떻게 해야될지 알려주시면 감사하겠습니다.
(해당 flag를 지우고나서 run은 실행이 되긴합니다.)

**Comment by nsml-admin** [comment]
안녕하세요,

해당flag를 지우고 실행하시면 됩니다. (현재는 readme에 다시 반영하였습니다)

감사합니다

**Comment by hjlee9182** [comment]
감사합니다
