### ISSUE TITLE
혐오댓글 분류로 과제 진행하고 싶은데 nsml 튜토리얼 연습용으로 스팸이미지 이용해봐도 되나요?

### ISSUE THREAD

**Issue by dhsimpson** [AI-RUSH-Operation/NAVER-AI-RUSH#28]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**

제목과 내용이 같습니다.
nsml 플랫폼에서 train 부터 submit 까지 연습 해보고 싶어서요!

**Comment by bluebrush** [comment]
@dhsimpson 님, 참가 문제에게 submit하실수 있습니다. 두 번째 dataset이 늦게 제공되어 불편을 드렸습니다.  ;;
