### ISSUE TITLE
세션 리스트 확인(nsml ps)

### ISSUE THREAD

**Issue by developer0hye** [AI-RUSH-Operation/NAVER-AI-RUSH#29]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**: 
Built: 2020-07-15T13:50:45+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: windows
Revision: e4648bbaa786680251194e50e60803da35dc201b (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
developer0hye

**Question**

테스트로 실행한 세션들을 삭제하고자 nsml ps 명령어를 사용하여 세션 이름을 확인하려 했습니다.

그런데, nsml ps 명령어를 입력한 결과 세션이 없는 것으로 출력됐으며, nsml info 명령어를 입력하였을 때는 2개의 세션이 존재하는 것으로 확인됐습니다. 정상적인 결과인가요??

감사합니다.

![image](https://user-images.githubusercontent.com/35001605/87507728-dba43a80-c6a8-11ea-9694-abbb866da809.png)

**Comment by wookiekim** [comment]
`nsml ps -a` 를 하면 종료된 세션까지 보이는 것으로 알고 있습니다 !.!

**Comment by developer0hye** [comment]
@wookiekim 
감사합니다! 문제가 해결되어서 해당 이슈는 닫도록 하겠습니다.
