### ISSUE TITLE
nsml login이 안됩니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#3]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**
![image](https://user-images.githubusercontent.com/46337218/87387201-2fe1e880-c5dd-11ea-90d6-1cc690546ccc.png)

웹에서랑 window에서 cmd로 열어서 로그인 시도를 하였는데 로그인이 되지않습니다.

**Comment by bluebrush** [comment]
@hjlee9182 님. 
https://airush.nsml.navercorp.com/download 이곳에서 새로운 CLI를 받으시면 됩니다. 위 주소는 다른 인스턴스용 CLI입니다. 
#1  참조 바랍니다.

**Comment by hjlee9182** [comment]
감사합니다
