### ISSUE TITLE
User session excited without any notice

### ISSUE THREAD

**Issue by Jasonlee1995** [AI-RUSH-Operation/NAVER-AI-RUSH#30]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**: e4648bbaa786680251194e50e60803da35dc201b

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Jasonlee1995

**Question**
![image](https://user-images.githubusercontent.com/49643709/87508655-dcd66700-c6aa-11ea-99c2-85b3efcda1ed.png)

학습을 위해서 돌리는 도중 따로 건드린 부분이 없는데 killed되면서 session이 종료되었습니다.
혹시 어떤 부분때문에 발생했는지 알 수 있을까 싶어서 문의드립니다.
일단 baseline을 돌려보고자 하였는데 그것도 수행이 되지를 않아서 문의드립니다.

**Comment by bluebrush** [comment]
안녕하세요. 아래와 같은 이유로 종료되었습니다. 
자원 사용량그래프는 아래 위치에서 확인 가능합니다. 
--memory 옵션을 적절히 사용하거, 코드의 수정을 고려해보는 게 좋을 것 같습니다. 
https://airush.nsml.navercorp.com/overview/Jasonlee1995/spam-1/11

```
$ nsml inspect Jasonlee1995/spam-1/11
----------  ------------------------------
Status      exited
Running     False
Paused      False
Restarting  False
OOMKilled   False
Dead        False
Pid         0
ExitCode    137  => OOM(out of memory) 강제 종료
Error
StartedAt   2020-07-15T04:15:12.767282075Z
FinishedAt  2020-07-15T05:23:27.740944387Z
----------  ------------------------------
```
