### ISSUE TITLE
submit -t 는 사용이 안되는건가요?

### ISSUE THREAD

**Issue by hyeinhyun** [AI-RUSH-Operation/NAVER-AI-RUSH#32]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: MAC
- **client version(please show nsml --version)**:
Built: 2020-07-15T13:50:45+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: darwin
Revision: e4648bbaa786680251194e50e60803da35dc201b (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hyeinhyun

**Question**
nsml submit -t 로 제출전 테스트를 진행하고자하였는데, 1시간이 넘어도 계속 세션이 돌아가고 있습니다. 확인부탁드립니다 🙏

**Comment by nsml-admin** [comment]
submit 시에는 stdout로그가 보이지않아서 submit -t 로 생성한 세션안에서 stdout을 확인하는 용도입니다.

`nsml logs [session]`으로 생성된 세션의 로그를 확인하고, 에러를 본후에 `nsml submit` 명령어로 제출하시면 됩니다.

**Comment by hyeinhyun** [comment]
그럼 자동으로 세션이 꺼지지 않는거군요. 감사합니다.
