### ISSUE TITLE
학습을 하지 않는 새로운 세션 생성 시 에러가 발생합니다.

### ISSUE THREAD

**Issue by Ye-Ji-Kim** [AI-RUSH-Operation/NAVER-AI-RUSH#33]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Ye-Ji-Kim

**Question**
올려주신 load model in a session을 보면서 코드를 삽입하고 새로운 세션을 run 하고 log를 확인하였더니 다음과 같은 에러가 뜹니다.
![image](https://user-images.githubusercontent.com/47693695/87511253-fa59ff80-c6af-11ea-9646-d638d525b68c.png)

**Comment by nsml-admin** [comment]
load를 하려는 세션의 이름과 모델명,
load하려다 실패한 세션의 이름을 알려주시기 바랍니다.

**Comment by Ye-Ji-Kim** [comment]
Ye-Ji-Kim/spam-1/1 세션의 'best'  모델을 Ye-Ji-Kim/spam-1/3 세션에서 load하였을 때 실패하였습니다.

**Comment by nsml-admin** [comment]
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/35#issuecomment-659202232 와 마찬가지로 사용하는 프레임워크가 달라서 발생한 문제입니다.

번거롭겠지만 새로 훈련을 해주시기 바랍니다

감사합니다
