### ISSUE TITLE
Error for submission

### ISSUE THREAD

**Issue by Jasonlee1995** [AI-RUSH-Operation/NAVER-AI-RUSH#36]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: window
- **client version(please show nsml --version)**: e4648bbaa786680251194e50e60803da35dc201b

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Jasonlee1995

**Question**
![image](https://user-images.githubusercontent.com/49643709/87535224-1b334c80-c6d2-11ea-8b50-6097fae7c826.png)
Submission error이 계속 발생합니다.
Session을 중지할 수도 없고 계속 running인지라 어떠한 문제때문에 발생하는지 문의드립니다.

**Comment by bluebrush** [comment]
@Jasonlee1995 님, submit 과정은 log로 trace할 수 없도록 설계되어 있습니다. submit과정은 최대 1시간까지 유지될 수 있으며, 이후 자동 종료됩니다. 
위 오류 메시지는 submit 세션이어서 log를 볼수 없어 발생하는 것으로 표현 정보가 부족하여 혼란을 드린것 같습니다.
