### ISSUE TITLE
세션 삭제가 안됩니다.

### ISSUE THREAD

**Issue by dhsimpson** [AI-RUSH-Operation/NAVER-AI-RUSH#37]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**

nsml web에서 session을 삭제 시도했더니 진행중 세션을 중단한 뒤 삭제하라 합니다.
중단하기 위해 stop 버튼을 누르니 세션 status 변경 실패 에러가 뜹니다.
세션 이름은 dhsimpson/hatespeech-1/7 입니다.

**Comment by dhsimpson** [comment]
p.s. Allocating 이 로그에 계속 찍힙니다.
제가 cli에서 엔트리를 run시켜 새 세션을 만들려다가 중간에 ctrl+c 로 중단시켰는데, 그것이 문제가 된 걸까요?

**Comment by bluebrush** [comment]
@dhsimpson 님, 조금 기다리시면 돌 것 같습니다. 
docker base image 변경시 해당 이미지를 download 받아서 build하는 시간이 필요합니다. 이 과정이 allocatiing으로 나오며, 이 단계에서는 취소가 불가능합니다.
