### ISSUE TITLE
Submission error

### ISSUE THREAD

**Issue by Jasonlee1995** [AI-RUSH-Operation/NAVER-AI-RUSH#39]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: window
- **client version(please show nsml --version)**: e4648bbaa786680251194e50e60803da35dc201b

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Jasonlee1995

**Question**
![image](https://user-images.githubusercontent.com/49643709/87544115-debb1d00-c6e0-11ea-8bfa-3a66050ed79c.png)

Submission을 하고 1시간이 지났음에도 자동으로 종료가 되지 않고 있습니다. (2시간 째 돌아가는중)
Pause를 누르려고해도 안되며 삭제 또한 되지 않습니다.
혹시 어떻게하면 되는지 싶어서 문의드립니다.

**Comment by eedn** [comment]
저도 spam-1 의 baseline 을 submission하는데 자꾸 1시간 지나서 timeout 됩니다... ㅠㅠㅠㅠ
그런데 저같은 경우는 1시간이 지난 후에 세션은 멈추는것 같아요.
login ID : eedn

**Comment by Jasonlee1995** [comment]
![image](https://user-images.githubusercontent.com/49643709/87614000-d64afc80-c749-11ea-8516-665912e58063.png)
현재까지도 종료가 되지 않고 있습니다.
Baseline을 그대로 돌렸으며, 혹시 강제 종료 방법을 말씀해주시면 감사하겠습니다.

**Comment by nsml-admin** [comment]
안녕하세요, 

안지워지는 세션같은경우는 터미널창에서 (cli에서) 
`nsml rm -f [session]`을 입력하면 삭제할수있습니다.

현재는 Jasonlee1995/spam-1/14 Jasonlee1995/spam-1/15 세션을 삭제한 상태입니다

감사합니다.
