### ISSUE TITLE
CLI에서만 로그인이 안되는 문제

### ISSUE THREAD

**Issue by jayten-jeon** [AI-RUSH-Operation/NAVER-AI-RUSH#4]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: 
Mac
- **client version(please show nsml --version)**:
```
Built: 2020-04-21T11:27:44+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: darwin
Revision: da15d512441a71a223d8c678f7e94e6421627c29 (not-modified)
Preconfigured connection: ai-cli.nsml.navercorp.com:443
```

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
jayten42

**Question**
`https://airush.nsml.navercorp.com/`  에서는 로그인이 되었으나, CLI환경에서는 로그인이 되지 않습니다.

**Comment by bluebrush** [comment]
@jayten42 님, CLI 터미널 로그 전체 긁어서 올려주세요.

**Comment by jayten-jeon** [comment]
@bluebrush 
![image](https://user-images.githubusercontent.com/57934461/87388022-e4303e80-c5de-11ea-9ea8-c924361ebb5f.png)

**Comment by bluebrush** [comment]
@jayten42 님.
https://airush.nsml.navercorp.com/download 이곳에서 새로운 CLI를 받으시면 됩니다. 위 주소는 다른 인스턴스용 CLI입니다.
#1 참조 바랍니다.

**Comment by jayten42** [comment]
connecting 주소를 보니 airush 주소가 아니네요 mac 버전 cli 확인 부탁드립니다.

**Comment by jayten-jeon** [comment]
https://airush.nsml.navercorp.com/download
링크에서 다운받아서 해결 했습니다!
