### ISSUE TITLE
Failed to open tensorboard

### ISSUE THREAD

**Issue by kingsj0405** [AI-RUSH-Operation/NAVER-AI-RUSH#40]
**Informations**
#### CLI
Not related

#### WEB
- **Brower (chrome, firfox, etc)**: Microsoft Edge
- **URL**: http://cvairush011.clova.nfra.io:25308/

**What is your login ID?**
kingsj0405

**What is name of session in problem? (bug message or screenshot)**
kingsj0405/spam-1/4

![image](https://user-images.githubusercontent.com/13496612/87547167-aa962b00-c6e5-11ea-8902-31cde7ba7a9f.png)

**How often does it occur?**

everytime

**Steps to reproduce the problem**

Go to 'graph' tab.
Select 'tensorboard' on dropbox
Move to hyperlink on notice(?).(http://cvairush011.clova.nfra.io:25308/ in this case)

![image](https://user-images.githubusercontent.com/13496612/87547198-b8e44700-c6e5-11ea-9500-907ad65241a8.png)

**What is the expected behavior?**

Tensorboard

![image](https://user-images.githubusercontent.com/13496612/87547380-f943c500-c6e5-11ea-9b7a-ac388d3aa8bf.png)

**Suggested solutions**

Maybe there can be a problem with dynamic port forwarding...?

**Comment by nsml-admin** [comment]
안녕하세요.

nsml에선 nsml.report를 사용해서 그래프를 그릴수가 있습니다.

report를 사용하면 tensorboard에서도 보실수있는데요,

https://n-clair.github.io/nlp-challenge-docs/_build/html/ko_KR/contents/web_interface/graph.html 문서를 참고해보시기 바랍니다.

**Comment by kingsj0405** [comment]
넵 감사합니다.
