### ISSUE TITLE
혐오댓글 데이터관련하여 문의드립니다.

### ISSUE THREAD

**Issue by Namsik-Yoon** [AI-RUSH-Operation/NAVER-AI-RUSH#42]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

Namsik-Yoon
**Question**
혐오댓글 데이터관련하여 문의드립니다.

레이블된 데이터 10만개와 레이블되지않은 데이터 230만개가 있다고 알고있는데,
레이블되지않은 데이터 230만개는 어떻게 얻을수있는지 알수있을까요?

**Comment by kingheadcat** [comment]
@Namsik-Yoon 안녕하세요.
해당 데이터는 재 검수중에 있습니다.
빠르면 익일 중으로 업데이트 될 예정입니다.
