### ISSUE TITLE
multi gpu 사용한 session submit시 질문입니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#43]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**

ValueError: To call `multi_gpu_model` with `gpus=5`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1', '/gpu:2', '/gpu:3', '/gpu:4']. However this machine only has: ['/gpu:0', '/cpu:0']. Try reducing `gpus`.

단순히 -g 옵션을 주는것만으로 multi gpu가 되지않아( 사용량이 늘지 않습니다.) 
코드 내부에서 multi gpu가 동작하도록 작성하였고 각 gpu가 다 사용되는 것을 확인하였습니다.
하지만 이렇게 코드를 작성한 session을 제출을 하면 위와 같은 오류가 발생하면서 submit이 되지않습니다.
마지막 문장을 보아 submit에서 gpu가 하나만 할당되어 multi gpu코드를 못 받는것 같은데 
어떻게 해야할지 알려주시면 감사하겠습니다.

**Comment by bluebrush** [comment]
@hjlee9182 님, 말씀하신 문제의 해결을 위해서 CLI를 다시 배포하였습니다. login 새로 하시면 update될 것 입니다. 문제 사항정리해주셔서 감사합니다. #45 에서 반영되었습니다.

**Comment by hjlee9182** [comment]
@bluebrush 감사합니다 ^^
