### ISSUE TITLE
run과정에서 생기는 에러

### ISSUE THREAD

**Issue by dlckdtn62** [AI-RUSH-Operation/NAVER-AI-RUSH#46]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
dlckdtn62
![에러메세지](https://user-images.githubusercontent.com/50452621/87638384-a79b4900-c77e-11ea-8faa-037b27e3cbc1.PNG)

**Question**
저런식으로 에러가 나오게 되는데 어떻게 해결할 수 있을까요??

**Comment by nsml-admin** [comment]
안녕하세요.

서버상의 문제였던거같은데요, 다시 시도해보시면 될것같습니다

감사합니다.
