### ISSUE TITLE
submission 실패

### ISSUE THREAD

**Issue by eedn** [AI-RUSH-Operation/NAVER-AI-RUSH#48]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**:
![image](https://user-images.githubusercontent.com/15064927/87646429-cb17c100-c789-11ea-8f10-fb1f294647f5.png)

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**: 

**What is your login ID?**
eedn

**Question**
baseline으로 train하고 submit을 시도중인데 계속 실패중에 있습니다..ㅠㅠ
![캡처](https://user-images.githubusercontent.com/15064927/87646526-ee427080-c789-11ea-9901-99c9eafdeba3.PNG)
![캡처2](https://user-images.githubusercontent.com/15064927/87646543-f1d5f780-c789-11ea-8cd6-aaab4ccee345.PNG)

document에 나와있는 방법대로 로드했다가 저장해도 submit에 계속 번번히 실패합니다.
좋은 방법 없을까요...

**Comment by nsml-admin** [comment]
안녕하세요. 
공지에도 말씀드렸었지만 첫번째 baseline이 올라갔을때 오류가 있었습니다. 
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/25 
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/13

현재는 수정된 버전이 새로 업데이트되었는데요, 

새로 업데이트된 baseline으로 submit을 진행해주시기 바랍니다

불편을드려서 죄송합니다

**Comment by eedn** [comment]
client만 업데이트 된 걸로 착각했습니다.
다시 다운받아서 하니까 되네요. 감사합니다.
