### ISSUE TITLE
submit not respond 오류

### ISSUE THREAD

**Issue by teang1995** [AI-RUSH-Operation/NAVER-AI-RUSH#49]
nsml submit teang1995/spam-1/1 best 

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: window 8
- **client version(please show nsml --version)**:  별첨

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**:

**What is your login ID?** teang1995

**Question**
submit한 후 기다리는데 아래와 같은 에러가  nsml에서 확인되었습니다.
![image](https://user-images.githubusercontent.com/23451721/87649850-ca802a00-c78b-11ea-8be9-aaa357372e8f.png)
![image](https://user-images.githubusercontent.com/23451721/87649888-d4a22880-c78b-11ea-9e60-b99a6d370dc5.png)

이 전에 하나의 세션의 모델에 대해 두 번 submit을 시도하였고, 두 번 모두 되지 않아 세션을 삭제한 뒤 다시 생성해 제출하였는데도 문제가 생깁니다. 어떤 문제인지 궁금합니다.

**Comment by nsml-admin** [comment]
안녕하세요.

https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/48#issuecomment-659253086 문제와 마찬가지로, 새로운 baseline을 받고나서 다시 시도해보시기 바랍니다.

감사합니다.

**Comment by teang1995** [comment]
@nsml-admin  답변 주신 내용으로 해결하였습니다. 정말 감사합니다.
