### ISSUE TITLE
1라운드 문제 중 하나만 선택해서 진행해야 하나요?

### ISSUE THREAD

**Issue by jayten-jeon** [AI-RUSH-Operation/NAVER-AI-RUSH#5]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
jayten42

**Question**
1라운드 문제인 **스팸이미지 필터링**, **혐오댓글 필터링** 중 하나만 택해서 진행해야 하나요?
아니면 두 문제 모두 참여해도 상관 없나요?

**Comment by bluebrush** [comment]
현재 추가 검토중입니다. 곧 답변 예정입니다.

**Comment by taehee3088** [comment]
안녕하세요. 

2문제 중에 희망하는 문제 1개만 선택 가능합니다.
