### ISSUE TITLE
nsml 로그인이 안됩니다. 

### ISSUE THREAD

**Issue by boychaboy** [AI-RUSH-Operation/NAVER-AI-RUSH#51]
월요일 자정 전에 신청서를 제출했는데 아직 제 GitHub 아이디로 nsml 로그인이 안됩니다. 
제 github아이디는 boychaboy 입니다. 확인 부탁드립니다. 

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**

**Comment by bluebrush** [comment]
#1 번 참고해서, CLI 다시 받아서 확인바랍니다. 오류가 지속되면, 오류 메시지 전체를 붙여주시면 확인가능할 것 같습니다.
