### ISSUE TITLE
Submit시 발생하는 에러 입니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#53]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
![image](https://user-images.githubusercontent.com/46337218/87681419-9cb1da00-c7b9-11ea-8b28-91e8472c6bd6.png)

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**
![image](https://user-images.githubusercontent.com/46337218/87681245-70965900-c7b9-11ea-9ea9-f87894564003.png)

위와 같은 에러가 발생하여서 submit을 할수가 없습니다.
-t 옵션을 붙여서 submit을 하였을때는 아래처럼 아무런 말 없이 마무리가 됩니다.
하지만 그냥 submit할경우 에러가 발생합니다.
해결방안 알려주시면 감사하겠습니다.

**Comment by nsml-admin** [comment]
Precision과 recall을 구하는 과정에서 0/0 과 같은 케이스가 나와 생기는 문제입니다. 현재 0/0 = 0으로 처리하여 에러를 해결하였습니다.

**Comment by hjlee9182** [comment]
@nsml-admin 감사합니다 !
