### ISSUE TITLE
Ban 되었습니다.

### ISSUE THREAD

**Issue by justHungryMan** [AI-RUSH-Operation/NAVER-AI-RUSH#54]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
justHungryMan

**Question**

명령어를 잘못 수행해서 ban 되었습니다.
이곳에 문의하면 되나요?

**Comment by bluebrush** [comment]
@justHungryMan 님, ban 해제해 드렸습니다.
