### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by Jasonlee1995** [AI-RUSH-Operation/NAVER-AI-RUSH#55]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Window
- **client version(please show nsml --version)**: abae53dd3589a47d7f89a40128cb86176123f7ec (not-modified)

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Jasonlee1995

**Question**
![image](https://user-images.githubusercontent.com/49643709/87741315-2cd63a80-c81f-11ea-903b-c6e7aac91d33.png)
Setup.py에 tensorflow==2.2라고 하였더니 docker image가 빌드가 되지 않는다고 에러가 뜹니다.
Docker image가 #으로 가져오는 것이고 밑에 있는 setup()에서 pip로 설치할 라이브러리를 적는것으로 이해하였는데, 제가 잘못 이해하는 것인지 문의드립니다.

**Comment by nsml-admin** [comment]
안녕하세요.

수정하셨다는 setup.py를 올려주시면 확인해보겠습니다.

**Comment by Jasonlee1995** [comment]
다른 도커 이미지를 통해서 해결하였습니다!
