### ISSUE TITLE
Submission, model size 관련 질문.

### ISSUE THREAD

**Issue by justHungryMan** [AI-RUSH-Operation/NAVER-AI-RUSH#57]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
justHungryMan

**Question**
혹시 submit 할 때 제한된 모델 사이즈가 있나요?
Code 에서 모델 사이즈만 변경중인데 이전에는 제출이 되었는데 모델 사이즈를 키우니 제출이 안되서 질문드립니다.

**Comment by wookiekim** [comment]
150MB 제한이 있다고 하셨던 것 같기도 합니다

**Comment by justHungryMan** [comment]
@wookiekim 
150MB 는 아닌듯합니다.

340MB 는 통과되고 493, 600+ MB 에 대하여 submit 이 안되고있습니다.

**Comment by nsml-admin** [comment]
안녕하세요,
아마도 다른부분에서 에러가 났을걸로 생각되는데요

실행했던 명령어와 실행후 발생한 세션네임 (가능하면 ) 알려주시기 바랍니다.
에러내용도 있으면 첨부 부탁드립니다

**Comment by developer0hye** [comment]
@nsml-admin @wookiekim  

저도 ot 당시에 최대 모델 사이즈를 150MB 로 제한한다는 내용을 들었습니다.

모델 사이즈에 대한 제한은 없는 것인가요?

**Comment by justHungryMan** [comment]
<img width="695" alt="스크린샷 2020-07-17 23 11 31" src="https://user-images.githubusercontent.com/18109378/87795342-df8bb480-c882-11ea-9fe7-9d749683a1ac.png">

@nsml-admin  
단지 모델 사이즈만 크게하였는데 submit 이 되지 않습니다.
수행기록 첨부합니다.

**Comment by nsml-admin** [comment]
@justHungryMan  세션의 gpu 메모리 사용량을 확인해보니, 100%를 찍고 세션이 종료되었습니다.

모델사이즈의 제한은 없는데 gpu메모리 사이즈(24G)보다 많은값을 사용하려고해서 에러가 발생하면서 종료된거같습니다.

**Comment by justHungryMan** [comment]
@nsml-admin  감사합니다. 혹시 이런 로그를 저희쪽에서는 알 수 없나요?
