### ISSUE TITLE
nsml 로그인이 갑자기 안됩니다(no such host)

### ISSUE THREAD

**Issue by kimwj94** [AI-RUSH-Operation/NAVER-AI-RUSH#58]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
kimwj94

**Question**
어제 잘 로그인했었는데 오늘은 안되네요.
![캡처](https://user-images.githubusercontent.com/37704174/87767417-996c2c00-c855-11ea-9e74-0144a8c11153.JPG)

**Comment by bluebrush** [comment]
@kimwj94 님. network문제로 보이는데요.. 주로 방화벽이 있는 건물/장소에서 발생할 수 있습니다. 다른 네트웍 환경에서 테스트바랍니다. 
아 두 명령의 실행 전체 결과를 보여주시면 더 명확하게 확인가능합니다. 
```
ping airush-cli.nsml.navercorp.com
telnet airush-cli.nsml.navercorp.com 10001
```

**Comment by kimwj94** [comment]
@bluebrush 아 제가 생각해보니 어제 접속했던 네트워크 환경과 달랐네요.
해결했습니다. 감사합니다.
