### ISSUE TITLE
Ban 해제 부탁드립니다.

### ISSUE THREAD

**Issue by developer0hye** [AI-RUSH-Operation/NAVER-AI-RUSH#59]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**:
Built: 2020-07-16T14:06:32+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: windows
Revision: abae53dd3589a47d7f89a40128cb86176123f7ec (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**:  chrome
- **URL**:

**What is your login ID?** 
developer0hye

**Question**
세션에 존재하는 모델을 삭제하는 과정에서 서버로부터 ban 이 되었습니다.
해제 부탁드립니다.

**Comment by bluebrush** [comment]
@developer0hye 님, 해제하였습니다.

**Comment by developer0hye** [comment]
@bluebrush 감사합니다!
