### ISSUE TITLE
NSML 로그인 불가

### ISSUE THREAD

**Issue by thejungwon** [AI-RUSH-Operation/NAVER-AI-RUSH#6]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Mac OS
- **client version(please show nsml --version)**:
```
Built: 2020-04-21T11:27:44+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: darwin
Revision: da15d512441a71a223d8c678f7e94e6421627c29 (not-modified)
Preconfigured connection: ai-cli.nsml.navercorp.com:443
```

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
thejungwon

**Question**
웹과 CLI 둘다 등록이되지 않은 유저라고 하며 접속이 불가합니다. 
확인 부탁드립니다~!

**Comment by wookiekim** [comment]
저도 현재 안되고 있습니다. ID는 wookiekim입니다!

**Comment by bluebrush** [comment]
@thejungwon @wookiekim 님, 두분 모두 터미널 CLI오류 메시지 전체를 부탁드립니다.

**Comment by thejungwon** [comment]
```
nsml_client.darwin.amd64.hack nsml login
INFO[2020/07/14 14:59:42.142] connecting to ai-cli.nsml.navercorp.com:443
GitHub Username: thejungwon
GitHub Password: *********
FATA[2020/07/14 14:59:48.411] login failed: You are not a registered user
```
다음과 같습니다.

**Comment by bluebrush** [comment]
@thejungwon 님,  #1 의 CLI 링크에서 새로 받으시면 될것 같습니다.

**Comment by ddamddi** [comment]
새로 올려주신 링크를 통해 다운받고 로그인을 했는데 웹은 로그인이 되지만 CLI는 로그인이 되지않습니다.
CLI 오류메세지도 같이 첨부합니다.

```
INFO[2020/07/14 15:00:39.453] connecting to airush-cli.nsml.navercorp.com:10001 
GitHub Username: leonardkkh@gmail.com
GitHub Password: *************
FATA[2020/07/14 15:00:49.530] login failed: You are not a registered user  
```

**Comment by thejungwon** [comment]
> @thejungwon 님, #1 의 CLI 링크에서 새로 받으시면 될것 같습니다.

감사합니다! 잘 동작합니다!

**Comment by bluebrush** [comment]
@ddamddi 님, ID란에 ddamddi 를 넣어시고, github 비번을 치시면 될 것 같습니다.

**Comment by wookiekim** [comment]
> @thejungwon 님, #1 의 CLI 링크에서 새로 받으시면 될것 같습니다.

감사합니다!

**Comment by ddamddi** [comment]
> @ddamddi 님, ID란에 ddamddi 를 넣어시고, github 비번을 치시면 될 것 같습니다.

잘 동작합니다! 감사합니다!!
