### ISSUE TITLE
session 상태 Zombie

### ISSUE THREAD

**Issue by limaries30** [AI-RUSH-Operation/NAVER-AI-RUSH#61]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
limaries30

**Question**

session 상태가 Zombie 라고 나오는데, 이는 무엇을 의미하는 것인가요?

![image](https://user-images.githubusercontent.com/46235538/87777020-b3ad0680-c863-11ea-8033-16427b7a0a15.png)

**Comment by bluebrush** [comment]
@limaries30 님,zombie세션은 GPU를 할당받은 수 util이 0을 지속적으로 기록하는 세션입니다. GPU를 2개 할당후, 1개만 사용해도 동일하게 표시되며, 동작 및 학습에는 영향을 주지 않으니 참고바랍니다.
