### ISSUE TITLE
Hatespeech unlabeled data접근

### ISSUE THREAD

**Issue by fenneccat** [AI-RUSH-Operation/NAVER-AI-RUSH#63]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**
hatespeech에서 unlabeled data를 사용하려면 어떻게 접근해야하나요?

**Comment by bluebrush** [comment]
@fenneccat 님,  아래 링크가 답변이 될 수 있을까요?
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/69#issuecomment-660918314
