### ISSUE TITLE
매주차 데이터셋 질문입니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#67]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**
매주 새로운 데이터셋이 올라온다고 하셨는데 해당 데이터셋은 매주 월요일마다 업로드 인가요? 
언제 업로드 되는건지 궁금합니다.

**Comment by bluebrush** [comment]
@hjlee9182님,  월요일 14시로 예정하고 있습니다.

**Comment by hjlee9182** [comment]
@bluebrush 감사합니다!!
