### ISSUE TITLE
Baseline 실행시 오류가 발생합니다.

### ISSUE THREAD

**Issue by jjxxmiin** [AI-RUSH-Operation/NAVER-AI-RUSH#7]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:

Window 10

- **client version(please show nsml --version)**:

Built: 2020-07-13T19:30:15+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: windows
Revision: dd3f91164a969f04d70f870cd2e42001db47b504 (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**:

Chrome

- **URL**:

**What is your login ID?**

jjeamin

**Question**

로그인은 되는데 baseline 실행시 error가 발생합니다.

```
nsml run -e nsml_train.py -d spam-1 -m "A good message" -g 1 -a "--experiment_name v1"
```

ERROR:

```
.Error: An error occurred while initializing user information. Please contact dev team
time="2020/07/14 14:48:39.472" level=fatal msg="Internal server error"
```

이메일에는 깃허브 인증코드가 도착하는데 인증코드를 적는란이 없습니다. 혹시 어떻게 해결할 수 있을까요?

**Comment by nsml-admin** [comment]
안녕하세요.

에러메세지는 깃허브 인증란이랑은 관련이 없습니다.

서버에 일시적인 오류가 발생해서 그런것같은데요 다시 run을 해보시면 될거같습니다.

감사합니다.

**Comment by jjxxmiin** [comment]
종료하고 실행하니 되네요 감사합니다!
