### ISSUE TITLE
spam2 제출시 해당 문제 발생합니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#72]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**
![image](https://user-images.githubusercontent.com/46337218/87904885-551d9d80-ca9a-11ea-8800-609fabcfaa06.png)

해결해주시면 감사하겠습니다.

**Comment by bluebrush** [comment]
@hjlee9182 님, 문제 확인되어 수정되었습니다. 현재 추가 테스트진행하고 있습니다.

**Comment by hjlee9182** [comment]
@bluebrush 감사합니다
