### ISSUE TITLE
spam-1에서 학습한 모델을 spam-2에서 다시 쓸수 없는건가요?

### ISSUE THREAD

**Issue by hyeinhyun** [AI-RUSH-Operation/NAVER-AI-RUSH#73]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hyeinhyun

**Question**
평가데이터만 업데이트인 경우, 
(이미 학습한)학습 모델 weight는 변화가 없을텐데, spam-1으로 학습한 모델을 spam-2에서는 사용하지 못하는건가요?

**Comment by bluebrush** [comment]
@hyeinhyun 님, 가능합니다. datset이 변경될 경우, spam-1 하위 세션의 model을 spam-2세션에서 load/store하는 단계가 필요합니다. 
https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/load_model.html 참고하시어, spam-1의 특정 세션의 model을 load하신수, save하시면 submit이 가능해집니다.

**Comment by hyeinhyun** [comment]
아! 확인했습니다 답변감사합니다 :)
