### ISSUE TITLE
NSML Tensorboard 이슈

### ISSUE THREAD

**Issue by whgusdn321** [AI-RUSH-Operation/NAVER-AI-RUSH#74]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**: Chrome
- **URL**:

**What is your login ID?**
whgusdn321

**Question**
안녕하세요,
NSML 웹상의 Graph - Tensorboard에서 스칼라 값이 아닌 이미지를 눈으로 보고싶은데, Graph부분에서 scalar부분만 제대로 나오고 Tensorboard를 클릭하면 
![image](https://user-images.githubusercontent.com/43023361/87906167-12a99000-ca9d-11ea-9d23-f55108a99353.png)
이 이미지가 나옵니다.

그리고, NSML Web의 Graph상에 있는 Tensorboard와 연동하려면 nsml.report()명령어를 사용해야하는데,
이렇게 하면 이미지가 연동되는게 맞나요..? (ndarray이미지를 python 2차원 list로 만들어서 report해줌)
![image](https://user-images.githubusercontent.com/43023361/87906630-f823e680-ca9d-11ea-82aa-b7569be1885e.png)
이렇게 했는데도 NSML Web상에서 Tensorboard를 누르면 첫번째 그림 처럼 안들어가집니다.

감사합니다..!

**Comment by bluebrush** [comment]
@whgusdn321 님, 현재 train 데이터의 이미지 view기능은 제공해드릴수 없습니다. train에 사용한 이미지는 법적 이슈등의 발생 소지가 있어 download 및 view제공을 해드리지 못하고 있습니다. 이점 양해부탁드립니다.

**Comment by whgusdn321** [comment]
아 그렇군요! 답변 감사드립니다 :)
