### ISSUE TITLE
spam 문제 모델 사이즈

### ISSUE THREAD

**Issue by developer0hye** [AI-RUSH-Operation/NAVER-AI-RUSH#75]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
developer0hye

**Question**

OT 때 모델 사이즈를 최대 150 MB 로 제한한다는 공지를 들었었습니다.

그런데 메일로 배포된 안내 자료에는 

이런 제한 사항이 기재되어있지 않은데

모델 사이즈 제한은 없는 것인가요??

**Comment by bluebrush** [comment]
@developer0hye 님, 여러 사람이 궁금해 하실 사항이라 공지에 달았습니다. #77

**Comment by developer0hye** [comment]
@bluebrush 감사합니다!
