### ISSUE TITLE
submit시 0점 관련 질문입니다.

### ISSUE THREAD

**Issue by hjlee9182** [AI-RUSH-Operation/NAVER-AI-RUSH#76]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
hjlee9182

**Question**
hjlee9182/spam-2/2 best

해당 체크포인트를 제출하였을때 0점이 나옵니다.
hjlee9182/spam-2/1 best 와 코드에서 차이점은 
![image](https://user-images.githubusercontent.com/46337218/87942731-fd9e2280-cad7-11ea-94a7-c96c486808e9.png)

1번은 preprocessing_function을 주석처리, 2번은 주석처리 하지않은것 밖에 없는데
1번은 제출시 정상적으로 점수가 나오고 2번은 점수가 0점이 나옵니다.

baseline코드에서 inference 관련부분은 건들지 않아서 아마 해당 부분 문제는 아닌것 같습니다.
코드 상에서 발생하는 문제가 아닌것 같아서 문의드립니다.

**Comment by nsml-admin** [comment]
https://github.com/AI-RUSH-Operation/NAVER-AI-RUSH/issues/68 과 마찬가지로 똑같은 값만 return되었습니다.

`nsml submit -t` 로 디버깅을 해보시기 바랍니다.

감사합니다.

**Comment by hjlee9182** [comment]
@nsml-admin 넵 알겠습니다.
