### ISSUE TITLE
nsml 로그인 문제

### ISSUE THREAD

**Issue by nill1024** [AI-RUSH-Operation/NAVER-AI-RUSH#78]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
nill1024

**Question**

제가 사정이 있어서 몇 개의 컴퓨터 환경에서 사용중인데 특정 컴퓨터에서 you are not registered user라고 뜨는 현상때문에 로그인이 안되네요.. 방법이 없나요?
![image](https://user-images.githubusercontent.com/37237414/88012601-4ba53b80-cb55-11ea-8ccb-6eb03f362547.png)

**Comment by Kitsunetic** [comment]
서버 주소를 봐서는 옛날 버전의 클라이언트를 쓰고 있는 것 같습니다.
AIRUSH가 시작되고 초창기에 서버 주소가 한번 바뀌었는데 그 이전 버전 같습니다.
클라이언트를 다시 다운받아서 해보실래요?

**Comment by nill1024** [comment]
> 서버 주소를 봐서는 옛날 버전의 클라이언트를 쓰고 있는 것 같습니다.
> AIRUSH가 시작되고 초창기에 서버 주소가 한번 바뀌었는데 그 이전 버전 같습니다.
> 클라이언트를 다시 다운받아서 해보실래요?

아 443이 주소였군요.. 감사합니다 해결했습니다!

**Comment by bluebrush** [comment]
@nill1024 님, port 뿐만 아니라 host 이름도 다르게 되어 있습니다. #1  참고하시 CLI 다시 받으시기 바랍니다.
