### ISSUE TITLE
터미널 로그인 불가 문의드립니다 (등록되지 않은 유저)

### ISSUE THREAD

**Issue by Clarit7** [AI-RUSH-Operation/NAVER-AI-RUSH#8]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Ubuntu 18.04.4 LTS
- **client version(please show nsml --version)**:
- **Full command line**:
(base) 1 jaylee@MLAI:~$ nsml --version
Built: 2020-04-21T11:27:44+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: linux
Revision: da15d512441a71a223d8c678f7e94e6421627c29 (not-modified)
Preconfigured connection: ai-cli.nsml.navercorp.com:443

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Clarit7

**What is name of session in problem? (bug message or screenshot)**
(base) 1 jaylee@MLAI:~$ nsml login
INFO[2020/07/14 14:57:17.951] connecting to ai-cli.nsml.navercorp.com:443  
GitHub Username: Clarit7
GitHub Password: *************
FATA[2020/07/14 14:57:26.715] login failed: You are not a registered user  

**How often does it occur?**
처음부터 지금까지 계속 발생중입니다

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by bluebrush** [comment]
#1 참고하시어 CLI 새로 받으시기 바랍니다.

**Comment by Clarit7** [comment]
감사합니다. 해결됐습니다.
