### ISSUE TITLE
Submit 테스트 도중 에러가 발생합니다.

### ISSUE THREAD

**Issue by OMMANT** [AI-RUSH-Operation/NAVER-AI-RUSH#80]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
Windows 10 Build 2004
- **client version(please show nsml --version)**:
Built: 2020-07-16T14:06:32+09:00
- **Full command line**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
OMMANT

**What is name of session in problem? (bug message or screenshot)**
![image](https://user-images.githubusercontent.com/33778020/88149390-fc393b00-cc3a-11ea-9e17-eedebfd70f20.png)

**How often does it occur?**

**Steps to reproduce the problem**
베이스라인에 따른 submit코드로 실행했지만
TF2.2.0으로 실행하면서 생긴 문제인지 KeyError가 발생합니다.
**What is the expected behavior?**

**Suggested solutions**

**Comment by nsml-admin** [comment]
안녕하세요.

에러내용을 보면 submit도중 코드에서 에러가 발생한거같습니다.
유저코드에서 발생한 에러의 디버깅을 도와드리긴 힘들것 같습니다.

감사합니다.
