### ISSUE TITLE
Submit Error - rpc error

### ISSUE THREAD

**Issue by Jasonlee1995** [AI-RUSH-Operation/NAVER-AI-RUSH#81]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Window
- **client version(please show nsml --version)**: abae53dd3589a47d7f89a40128cb86176123f7ec

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
Jasonlee1995

**Question**

![image](https://user-images.githubusercontent.com/49643709/88170106-17667380-cc58-11ea-847a-1f7480b1b339.png)

submit시 위와 같은 에러를 통해 inference를 할 수 없었습니다.

어떠한 이유 때문인지 문의드립니다.

**Comment by bluebrush** [comment]
@Jasonlee1995 님, submit 과정에서network이 끊어져서 발생한 것으로 추정됩니다. 아래에 오류메시지가 더 있는지 모르겠지만.. 아마도 다시 submit을 진행하셔야할 것으로 보여집니다.

**Comment by Jasonlee1995** [comment]
에러 메세지는 더 없었습니다. 다시 제출해보도록 하겠습니다!
