### ISSUE TITLE
로그인이 안됩니다.

### ISSUE THREAD

**Issue by kongjeongbae** [AI-RUSH-Operation/NAVER-AI-RUSH#82]
submit 기록을 확인하려 했더니 다시 로그인하라고 해서 했더니 로그인이 안됩니다. 확인부탁드립니다!
![image](https://user-images.githubusercontent.com/43724189/88248500-563e0d00-ccdc-11ea-95de-61cd14395e3a.png)

![image](https://user-images.githubusercontent.com/43724189/88248516-6524bf80-ccdc-11ea-8c5d-f56b2ecc7146.png)

**Comment by bluebrush** [comment]
현재 login 서버 등은 이상이 없는 것으로 확인됩니다. 
혹시, 문제가 지속되고 있으실까요? network 문제로 보여지는데요, 방화벽 등의 이슈로 추정됩니다. 
ping airush-cli.nsml.navercorp.com 이 동작하는지 확인가능할까요?

**Comment by kongjeongbae** [comment]
네 아직도 로그인이 안됩니다 ㅠ
![image](https://user-images.githubusercontent.com/43724189/88255256-e25b2f00-ccf2-11ea-80e2-7335c21deeb7.png)

**Comment by bluebrush** [comment]
회사,학교 등 단체라면, 방화벽으로 막혀진 상태로 보입니다. 다른 네트웍으로 테스트해보시고(테더링) 동작 한다면, 네트웍관리자에게 문의하셔야할 것 같습니다.

**Comment by kongjeongbae** [comment]
테더링으로 시도해봤는데 여전히 안됩니다 ㅠ 혹시나 다른 노트북으로도 테스트 해봤는데 기존 네트워크, 테더링 모두 로그인이 안되고 위와 같은 메시지가 발생하네요.. 혹시 다른 해결책이 있을까요??

**Comment by kongjeongbae** [comment]
테더링으로 다시 시도하니 로그인 됐습니다. 네트워크 문제인듯싶네요 ㅠ 답변 감사드립니다!
