### ISSUE TITLE
data를 주지 않은 session

### ISSUE THREAD

**Issue by fenneccat** [AI-RUSH-Operation/NAVER-AI-RUSH#86]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

**Question**
제가 테스팅해볼 것이 있어서, 따로 -d 옵션을 주지 않고 session을 만들었더니{이름}/None/1 session이 생기더라고요. 혹시 해당 세션을 NSML 웹상에서 제가 프린팅한 로그 등을 볼 수 있는 방법이 있나요? 아니면 킬하는 방법이 있는지도 궁금합니다.

**Comment by redleaf-kim** [comment]
nsml ps
세션리스트 볼수 있습니다.

nsml logs -f session_name
로그를 터미널상에서 확인할 수 있는데 30분이 한계인거  같습니다.

nsml rm -f session_name
해당 세션을 강제로 삭제가능합니다.
