### ISSUE TITLE
nsml.save('이름') 함수가 어떻게 동작되는것인가요

### ISSUE THREAD

**Issue by seokh1213** [AI-RUSH-Operation/NAVER-AI-RUSH#88]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Mac
- **client version(please show nsml --version)**: 
Built: 2020-07-16T14:06:32+09:00
Go: go1.12.17
GOARCH: amd64
GOOS: darwin
Revision: abae53dd3589a47d7f89a40128cb86176123f7ec (not-modified)
Preconfigured connection: airush-cli.nsml.navercorp.com:10001

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**:

**What is your login ID?** seokh1213

**Question**
nsml.save('이름') 함수가 어떤식으로 작동되는건가요 제가 만든 모델을 따로 지정하지 않는데 메모리에있는 모든것들이 저장이되는건가요?? network를 여러개를 사용해서 weight은 각각 저장하는데 여러개의 network weight들이 저장되어서 평가가 되는것인지 궁금합니다.

질문: nsml.save 함수가 모델을 지정하지 않는데 어떤것을 저장하는것인지 궁금합니다.

**Comment by fenneccat** [comment]
제가 이해하기로는 bind_model(모델)을 부르면 nsml이 해당 모델과 바인딩이 되어서, 이후에 nsml.save, load, infer를 사용할 시 bind_model 내부의 세 함수를 불러오는 것으로 추정합니다.

완벽히 이해를 한 것은 아니지만, slack 채널에 #things_didn't_work에 유사한 질문이 있는데 해당 쓰레드의 글들을 보고 모델 save, load하는데 어려움이 없었습니다. 한번 참고해보세요

**Comment by nsml-admin** [comment]
@fenneccat 님 답변 감사합니다!

말씀하신대로 nsml.bind에 넘겨진 함수들이 실행되는데요, 
submit 을 하면 코드내의 `nsml.pause()` 함수안에서 `nsml.bind` 에 넘겨진 함수들이 `load(), infer()`순으로 실행되고있습니다.

save도 마찬가지로 nsml.save()함수가 호출되면 `nsml.bind`에 넘겨진 save함수가 호출되고, save함수의 argument로 nsml에서 지정한 임의의 path가 넘겨지게 되는데 그부분에 모델관련 파일들을 저장하시면 nsml 클라우드에 저장되게 됩니다.

감사합니다.

**Comment by seokh1213** [comment]
감사합니다!!
