### ISSUE TITLE
login failed: You have been banned

### ISSUE THREAD

**Issue by thejungwon** [AI-RUSH-Operation/NAVER-AI-RUSH#92]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
thejungwon

**Question**
제가 nsml logs -f 명령어를 지금까지 학습한 모델들에 대해서 다 돌리다 보니, 너무 많은 요청을 동시에 보내서 그런지 계정이 막힌 것 같습니다.
풀어주시면 감사하겠습니다. 앞으로는 조심해서 쓰겠습니다. 
```
FATA[2020/07/26 15:00:21.376] login failed: You have been banned. Please contact the administrator.
```

**Comment by bluebrush** [comment]
@thejungwon 님, ban 해제하였습니다. 과도한 CLI 요청은 ban의 원인이됩니다. 주의부탁드립니다.

**Comment by thejungwon** [comment]
주의하겠습니다. 감사합니다!
