### ISSUE TITLE
Allocated상태가 지속되는 현상

### ISSUE THREAD

**Issue by qkek984** [AI-RUSH-Operation/NAVER-AI-RUSH#94]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **Full command line**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?** 
qkek984

**What is name of session in problem? (bug message or screenshot)**
 qkek984/spam-2/22

세션 할당단계중 커맨드라인에서 작업을 취소했습니다. 그랬더니 해당 세션은 중지나 삭제도 안되고 계속 Allocated상태로 자원만 차지하고 있습니다.

**How often does it occur?** 

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

"qkek984/spam-2/22" 작업 삭제해주시면 감사하겠습니다.

**Comment by wookiekim** [comment]
nsml rm -f (session-name) 으로 하면 강제로 종료되었던 것 같습니다!

**Comment by qkek984** [comment]
> nsml rm -f (session-name) 으로 하면 강제로 종료되었던 것 같습니다!

알려주셔서 감사합니다. 덕분에 해결됐습니다!
