### ISSUE TITLE
Allocating이 끝나지 않는 문제

### ISSUE THREAD

**Issue by azzyjk** [AI-RUSH-Operation/NAVER-AI-RUSH#95]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
azzyjk

**Question**
azzyjk/hate_3/5
해당 컨테이너를 run시키는 도중에 ctrl+c로 멈췄는데 무한 allocating에 걸리고 중지도 되지 않습니다.
혹시 조치해주실 수 있으신가요?
해당 컨테이너는 필요없어서 삭제해주시거나 정지해주시면 감사하겠습니다.

**Comment by wookiekim** [comment]
터미널에서 `nsml rm -f (session-name)` 을 실행하시면 강제종료 되는 것으로 알고 있습니다!

**Comment by azzyjk** [comment]
오 해결되었습니다. 감사합니다 :)
