### ISSUE TITLE
not enough resources for your request

### ISSUE THREAD

**Issue by redleaf-kim** [AI-RUSH-Operation/NAVER-AI-RUSH#96]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**
MaiHon

**Question**
<img width="759" alt="스크린샷 2020-07-27 오후 4 20 16" src="https://user-images.githubusercontent.com/41847456/88514441-100ee380-d025-11ea-8662-6f3b5006bd9c.png">
계속 해당 에러러가 뜨는데 어떻게 해야하나요?

확인해보니 gpu할당이 모두 되어서 제가 할당 받을수 있는 gpu가 없는것 같은데...

**Comment by justHungryMan** [comment]
@MaiHon nsml resource 를 보시면 할당 가능한 gpu가 나옵니다.
저도 몇일전부터 계속 새로고침 누르다가 자원 남으면 코드 돌리고 있네요..

**Comment by nill1024** [comment]
자원 쿼터가 계속 그대로인 상태인가요?
