### ISSUE TITLE
https://ai.nsml.navercorp.com/ 접속 불가

### ISSUE THREAD

**Issue by Sunghwan-DS** [AI-RUSH-Operation/NAVER-AI-RUSH#97]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**:

**What is your login ID?**
Sunghwan-DS

**Question**
https://ai.nsml.navercorp.com/ 접속 시도시
You are not a registered user. Please contact the administrator. ( dl_nsml_alpha@navercorp.com ) 라는 글과 함께 접속이 되지 않습니다. 확인 부탁드립니다.

**Comment by bluebrush** [comment]
@Sunghwan-DS 님, 혹시 접수번호 확인이 가능할까요?

**Comment by bluebrush** [comment]
@Sunghwan-DS 님, #1 게시글 보시고, 주소 재확인, CLI 다시 받으시면 될 것 같습니다.
