### ISSUE TITLE
[문의] 세션 삭제 불가 문제

### ISSUE THREAD

**Issue by wooks527** [AI-RUSH-Operation/NAVER-AI-RUSH#98]
nsml run 명령어를 실행 후 Allocation 중, 코드 수정을 위해 Ctrl + C로 명령어를 강제 취소했습니다.

그 이후로 해당 Session의 Terminal에서 "Allocating !"이라는 텍스트만 출력되며, Session 중지를 요청한 경우 "Failed to change the session status."라는 메시지로 알림이 뜨는 상황 입니다.

![infinite_allocating_problem_1](https://user-images.githubusercontent.com/32764235/88637432-1cfb0800-d0f5-11ea-8e3a-25a80252ee58.png)
![infinite_allocating_problem_2](https://user-images.githubusercontent.com/32764235/88637438-1e2c3500-d0f5-11ea-9377-e6b374567990.png)
![infinite_allocating_problem_3](https://user-images.githubusercontent.com/32764235/88637441-1e2c3500-d0f5-11ea-853e-c70d25d5f32d.png)

이 상태에서 Session 삭제 요청을 하면 "Please stop the session first."라는 메세지로 알림이 뜹니다.

![infinite_allocating_problem_4](https://user-images.githubusercontent.com/32764235/88637442-1ec4cb80-d0f5-11ea-8237-030c6434cac3.png)

현재 해당 세션이 Background에서 자원 할당 작업만 반복하는 좀비 프로세스가 된 것 같은데, 혹시 해당 프로세스를 kill 해 주실 수 있나요?

확인하시면 답변 부탁드리겠습니다.

**Comment by redleaf-kim** [comment]
nsml rm -f Session
으로 강제삭제 가능합니다.

**Comment by wooks527** [comment]
> nsml rm -f Session
> 으로 강제삭제 가능합니다.

답변 감사드립니다.
